export const GET_PLAYERS = "GET_PLAYERS"
export const GET_ERROR = "GET_ERROR"
export const GET_CLUBS = "GET_CLUBS"
export const SET_PAGE = "SET_PAGE"
export const GET_TEAMS = "GET_TEAMS"
export const GET_CAPTAINS = "GET_CAPTAINS"
export const SET_FILTER = "SET_FILTER"
export const GET_PLAYERS_TO_ADD = "GET_PLAYERS_TO_ADD"